sudo: required
services:
    - docker

before_install:
    - docker build -t hsjoberg/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true hsjoberg/react-test npm test

after_success:
    - docker build -t hsjoberg/multi-client -f ./client
    - docker build -t hsjoberg/multi-nginx -f ./nginx
    - docker build -t hsjoberg/multi-server -f ./server
    - docker build -t hsjoberg/multi-worker -f ./worker
    # Log into docker-hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push hsjoberg/multi-client
    - docker push hsjoberg/multi-nginx
    - docker push hsjoberg/multi-server
    - docker push hsjoberg/multi-worker
